### ISSUE TITLE
Comparison with Bidirectional WFA (BiWFA)

### ISSUE THREAD

**Issue by AndreaGuarracino** [CMU-SAFARI/Scrooge#1]
Hi, congratulations for your work. I appreciated the 'Memory-Frugal' terminology, very particular.

I wanted to point out that, in terms of memory usage, a quite killer algorithm is the bidirectional wavefront alignment algorithm (BiWFA), a recursive flavor of the standard WFA that popped up a few months ago. BiWFA computes the exact alignment in linear space with respect to the alignment score. You can see BiWFA's preprint at https://doi.org/10.1101/2022.04.14.488380, while its most updated implementation is in the [WFA2-lib](https://github.com/smarco/WFA2-lib) repository (`MemoryUltralow` mode). A(n in-depth) comparison between Scrooge and BiWFA in terms of memory usage would be tasty. :popcorn:

**Comment by joellindegger** [comment]
Hi Andrea

Thanks a lot for your feedback!
A rigorous comparison to linear memory methods like BiWFA and Hirschberg/Myers-Miller indeed makes a lot of sense.
I will see to it that we get it.

Some insights that I can share already are these:
1. A fairly unique property of the GenASM algorithm (and by extension Scrooge) is its *constant* memory complexity using the "windowing heuristic". This is beneficial especially for ultra-long sequences.
2. We have runtime comparisons to Edlib (linear memory complexity) and Darwin-GPU (constant memory complexity) in our arXiv paper here: https://doi.org/10.48550/arXiv.2208.09985

Best,
Joel

**Comment by RagnarGrootKoerkamp** [comment]
Hmm, it seems that for the paper you still compare to the affine alignment of WFA[1], instead of WFA2-lib which also has a dedicated implementation for unit costs. I'm not sure how much faster WFA2 is is compared to WFA1, but in my experience the unit-cost version is slightly faster, and indeed BiWFA should reduce memory usage and also provide a speedup.

From my own experiments, aligning n=10000 long sequences at 5% error rates takes around 0.001s, for a throughput of 1000/s (per thread). In the paper you report a throughput of around 20/s, so it would be good to figure out where this discrepancy comes from.

**Comment by joellindegger** [comment]
Hi both

We have added a comparison to the gap affine and edit distance versions of BiWFA from WFA2-lib in the supplementary materials: https://arxiv.org/pdf/2208.09985.pdf

Best,
Joel

**Comment by RagnarGrootKoerkamp** [comment]
Can you confirm that you run BiWFA in exact mode, without heuristics?

(I wasn't expecting BiWFA to be this much faster than WFA exact.)

**Comment by joellindegger** [comment]
Hi Ragnar

Sorry for the late reply.
Yes, if my understanding of the WFA2-lib interface is correct, these measurements are without any heuristics.

Here's the config we use:
```
    wavefront_aligner_attr_t attributes = wavefront_aligner_attr_default;
    attributes.distance_metric = gap_affine;
    attributes.affine_penalties.mismatch = agc.mismatch_cost;
    attributes.affine_penalties.gap_opening = agc.gap_open_cost;
    attributes.affine_penalties.gap_extension = agc.gap_extend_cost;
    attributes.memory_mode = wavefront_memory_ultralow;
    wavefront_aligner_t* const wf_aligner = wavefront_aligner_new(&attributes);
```

I assume the significant difference between WFA and BiWFA is mainly due to the also significant difference between on-chip vs off-chip memory bandwidths. I assume BiWFA will be able to keep everything on-chip in all cases, while WFA has to go off-chip due to too much memory footprint. Or at least it would go to a slower cache.

**Comment by RagnarGrootKoerkamp** [comment]
I believe that heuristics are enabled by default and you have to disable them explicitly. See here: https://github.com/smarco/BiWFA-paper/issues/8#issuecomment-1201195640

You should check the same for other calls to WFA2.

**Comment by smarco** [comment]
@RagnarGrootKoerkamp is right.

I stand by my words :-)
